import assert from "node:assert/strict";
import test from "node:test";

const expectedRuntimeExports = {
  "@civaapple/qi-agent": ["QiAgent", "InMemoryArtifactStore"],
  "@civaapple/qi-agent/capability": [
    "ASK_MODE_TOOLS", "InMemoryCapabilityBroker",
    "InMemoryCredentialBroker", "PLAN_MODE_EXTRA_TOOLS", "SESSION_MODES",
    "formatModeLabel", "isToolAllowedInMode", "mergeRedactionSummaries", "modeAllowsIntent",
    "nextSessionMode", "redactSensitiveText", "redactSensitiveValue", "toolsForMode",
  ],
  "@civaapple/qi-node/codeact": [
    "CodeActRunner", "ContainerProgramSandbox", "ControlledToolClient",
    "FixtureProgramSandbox", "buildContainerInvocation", "probeContainerRuntime",
  ],
  "@civaapple/qi-ai/context": [
    "ContextBudgetError", "approximateTokenEstimator", "compileContext", "estimateSerializedTokens",
  ],
  "@civaapple/qi-agent/extensions": [
    "Coordinator", "DECLARATIVE_RESOURCE_KINDS", "DELEGATED_BATCH_MAX", "DELEGATED_RESULT_MAX_CHARS",
    "DELEGATED_SUMMARY_PREVIEW_CHARS", "GraphGovernor", "MultiAgentBaselineGate",
    "PublicPackageMaturitySchema", "QI_SELF_SECTIONS", "QiSelfDecisionSchema", "QiSelfGapSchema",
    "QiSelfInvariantSchema", "QiSelfModelSchema", "QiSelfPackageSchema",
    "QiSessionInspectionError", "RuntimeMaturitySchema", "SelfModelPackageKindSchema",
    "contextBlocksFromRefs", "createQiIntrospectionTool", "createQiSelfContext",
    "createQiSessionInspectionTool", "inspectQiSession", "parseQiPluginManifest",
    "parseQiSelfModel", "qiSelfModel", "queryQiSelfModel", "runDelegatedBatch", "runDelegatedTurn", "validateGraph",
  ],
  "@civaapple/qi-agent/eval": [
    "DeterministicEvaluator", "EvaluatorCalibrationRegistry", "GoalEngine", "HumanEvaluator",
    "SemanticEvaluator", "evaluatorIdentity", "failureFingerprint",
  ],
  "@civaapple/qi-agent/kernel": [
    "ConcurrencyError", "InMemoryEventStore", "KERNEL_ASK_MODE_TOOLS",
    "KERNEL_PLAN_MODE_EXTRA_TOOLS", "StateTransitionError", "applySessionEvent",
    "isBootstrapSessionTitle", "replaySession", "sessionArchiveBlockers",
    "SESSION_TITLE_MAX_CHARS", "sessionTitleFromUserInput",
  ],
  "@civaapple/qi-ai": [
    "BUILTIN_PROVIDER_PROFILES",
    "ModelContentPartSchema", "ModelEventSchema", "ModelMessageSchema", "ModelRefSchema",
    "ModelRequestSchema", "OpenAIChatCompletionsModelPort", "OpenAIResponsesModelPort",
    "PortableToolSchema", "ScriptedModelPort", "assertProfileSupportsRequest",
    "camelizeCatalogKeys", "capOutputReserveTokens", "classifyProfileEndpoint",
    "createModelPortForProfile", "getProviderModelProfile", "getProviderProfile",
    "installProviderCatalog", "installProviderCatalogOverBuiltins",
    "listOpenAICompatibleModels", "listProviderProfiles", "mergeProviderCatalogs",
    "mergeProviderModels", "modelCapabilitiesFromProfile", "normalizeFunctionParameters",
    "normalizeKimiReasoningEffort", "normalizeReasoningEffort", "parseModelEvent",
    "parseModelRequest", "parseProviderCatalogDocument", "providerModelContextTokens",
    "providerModelOutputReserveTokens", "requireProviderProfile", "resetProviderCatalog",
    "resolveChatOutputTokenField", "resolveChatThinkingWire", "resolveModelCapabilities",
    "resolveOutputReserveWithDefault", "resolveProviderWireApi", "resolveProviderWireHints",
    "resolveResponsesThinkingWire", "thinkingAllowsDisable",
  ],
  "@civaapple/qi-agent/loop": [
    "ASK_MODE_TOOLS", "EventWriter", "GOAL_RESUME_DEMOTE_REASON", "HumanControlService",
    "PLAN_MODE_EXTRA_TOOLS", "SESSION_MODES", "SessionSupervisor", "SteeringMailbox", "TurnLoop",
    "applyGoalContinuationDecision", "canCompleteGoal", "createGoalContextBlock",
    "decideGoalContinuation", "demoteActiveGoalAfterResume", "firstIncompleteItem",
    "formatGoalContinuationNotice", "formatModeLabel", "formatPlanItemInput", "formatRunHistoryFacts",
    "isBatchWriteConflictResource", "isToolAllowedInMode", "latestTerminalPlanBoundRun",
    "nextSessionMode", "settleGoalBoundTurn", "toolsForMode", "tryCompleteGoalFromLedger",
  ],
  "@civaapple/qi-agent/tools": [
    "AuthorityDeniedError", "EffectReplayBlockedError", "StaleToolError", "ToolFailure",
    "ToolInputError", "ToolOutputError", "ToolRegistry", "defineTool",
  ],
  "@civaapple/qi-agent/effects": ["effectIdempotencyKey", "effectIntentHash"],
  "@civaapple/qi-node/mcp": [
    "McpBindingDriftError", "McpBridge", "McpConnectionManager", "McpDeclarationCatalog",
    "McpRemoteToolError", "McpReviewStore", "McpSchemaError", "SealedMcpOAuthProvider",
    "SealedMcpOAuthProviderFactory", "bindingKey", "candidateFromRaw", "createMcpCatalogTool",
    "createMcpLiveTool", "fingerprintMcpValue", "mcpTargetResource", "normalizeMcpOutput", "parseDeclaration",
  ],
  "@civaapple/qi-agent/memory": [
    "ContinuityController", "MemoryController", "MemoryIndexPendingError",
    "memoryRelevanceScore", "memoryScopeKey",
  ],
  "@civaapple/qi-protocol": [
    "ActionIdSchema", "EvaluationIdSchema", "EventIdSchema", "EvidenceIdSchema",
    "GoalBindingSchema", "GoalIdSchema", "LeaseIdSchema", "MemoryIdSchema", "MemoryScopeSchema", "PlanIdSchema",
    "PlanItemIdSchema", "QuestionIdSchema", "ReceiptIdSchema", "RunIdSchema",
    "RunImagePartSchema", "RunInputPartSchema", "SessionEventSchema", "SessionIdSchema", "SessionModeSchema", "StepIdSchema",
    "TaskIdSchema", "WorkItemIdSchema", "WorkPlanIdSchema", "assertSchema", "createId", "parseSessionEvent",
  ],
  "@civaapple/qi-node/scheduler": ["SessionEventTriggerSink", "SqliteWatcherScheduler"],
  "@civaapple/qi-node/storage": [
    "EncryptedFileCredentialStore", "SessionArchiveBlockedError", "SessionRepository",
    "SqliteEventStore", "SqliteMemoryIndex",
  ],
  "@civaapple/qi-node": [
    "QI_LAYOUT_GENERATION", "QI_LAYOUT_VERSION", "QI_PROJECT_LAYOUT_VERSION", "assertSafePrivateRoot",
    "canonicalWorkspacePath", "defaultProjectConfigPath", "defaultProjectsRoot",
    "defaultQiHome", "defaultSessionDataRoot", "discoverProjects", "ensureProjectLayout",
    "ensureProjectSessionLayout", "ensureQiLayout", "projectPaths", "projectSessionPaths",
    "qiStatePaths", "workspaceProjectId",
  ],
  "@civaapple/qi-node/extensions": [
    "DeclarativePackageStore", "WORKSPACE_QI_DIRECTORIES", "WORKSPACE_QI_FILES",
    "assertPinnedPackageSource", "resolveLayeredResources", "validateDeclarativeTree",
    "validateWorkspaceQiDirectory",
  ],
  "@civaapple/qi-node/skills": [
    "DEFAULT_SKILL_MAX_BYTES", "DEFAULT_SKILL_MAX_DEPTH", "DEFAULT_SKILL_MAX_FILES",
    "DEFAULT_SKILL_MAX_FILE_BYTES", "SKILL_NAME_PATTERN", "SkillCatalog", "SkillLoader",
    "SkillStaleError", "SkillUpdateIndeterminateError", "acquireImmutableSkillSource",
    "agentSkillLockHash", "assertSkillDirectoryName", "evaluateSkillReadiness", "loadAgentDefinition",
    "parseFrontmatter", "parseSkillMetadata", "readAgentSkillActivations", "readAgentSkillLock",
    "requireString", "runSkillScript", "writeAgentSkillActivations",
  ],
  "@civaapple/qi-node/stream": ["EventStreamService", "SessionEventHub", "encodeSseEvent", "sseStream"],
  "@civaapple/qi-node/tools": [
    "AuthorityDeniedError", "EffectReplayBlockedError", "FileArtifactStore",
    "SHELL_PROFILE_IDS", "StaleToolError", "ToolFailure", "ToolInputError",
    "ToolOutputError", "ToolRegistry", "artifactGetTool", "artifactTool", "assertSensitiveContentAllowed", "builtinTools",
    "cmdScriptHasNonAscii", "createFetchTool", "createWebMapTool",
    "createScriptTool", "createVerifyTool", "defaultVerificationManifestPath", "defineTool",
    "detectInstalledShellProfiles", "editTool", "fetchTool", "findTool", "findTrustedExecutable", "formatAccessiblePath",
    "formatCmdScriptContents", "formatCmdVersionLabel", "gitTool", "isRegularFile", "isSensitiveWorkspacePath",
    "joinWorkspaceRelative", "listTool", "loadVerificationProfiles", "mountsFromContext",
    "moveTool", "networkResource", "normalizeWorkspaceRelativePath", "platformShellCandidates",
    "prepareVerificationProfiles", "prewarmTrustedExecutables", "probeShellProfiles",
    "readPublicNetworkResource",
    "readTool", "removeTool", "resolveAccessiblePath", "resolveShellConfig",
    "resolveShellExecutable", "resolveWorkspaceEntry", "resolveWorkspacePath", "scanVerificationCandidates",
    "searchTool", "sensitivePathGrantsFromContext", "sensitivePathPolicyFromContext", "shellProfileResource",
    "shellTool", "treeTool", "verificationResource", "webMapTool",
    "textResponseLimitBytes", "windowsCommandInvocation", "writeCmdScriptFile", "writeTool", "writeVerificationManifest",
  ],
  "@civaapple/qi-node/media": [
    "DEFAULT_IMAGE_BYTE_BUDGET", "DEFAULT_IMAGE_MAX_EDGE_PX", "DEFAULT_READ_IMAGE_BYTE_BUDGET",
    "ImageIngestService", "MAX_IMAGES_PER_INPUT", "MAX_IMAGE_DECODE_PIXELS",
    "MAX_IMAGE_SOURCE_BYTES", "MAX_PREPARED_IMAGE_BYTES_PER_INPUT", "createReadImageTool",
    "detectImageInputCandidates", "detectImagePathCandidates", "detectImageUrlCandidates",
    "decodeFileUri", "normalizeImageMediaType", "prepareImageBytes", "sniffImageMediaType",
  ],
  "@civaapple/qi-tui": [
    "ComposerComponent", "FollowUpQueue", "FollowUpsComponent", "FormPanel",
    "LineInputBatcher", "ListPanel", "MultiSelectPanel", "NEW_SESSION_ID", "PanelHost", "QuestionPanel",
    "SESSION_PREVIEW_MAX_CHARS", "ScrollPanel", "SessionsPanel", "Theme", "TuiPresenter",
    "USER_MESSAGE_PREFIX", "applyTheme", "autocompleteSlashCommands", "buildSessionEntries",
    "collapsePreviewText", "commandHelp", "currentMark", "darkColors", "defaultLocale",
    "eventAffectsTranscript", "formatProviderLabel", "formatRelativeTime", "lightColors",
    "normalizeLocale", "padToDisplayWidth", "paintPromptWithCaret", "paletteFor", "panelFooter",
    "panelHeader", "panelRule", "parseMountsCommand", "parseSkillInstallCommand",
    "parseJobStopCommand", "parseTaskStopCommand", "parseTuiCommand", "pointer", "primarySlashCommands",
    "renderComposerPlaceholder", "renderEvent", "renderQiMark", "renderMarkdown",
    "renderStatus", "renderToolCard", "resolveThemeName", "sessionEntriesToPanelItems",
    "sessionPreviewText", "shortSessionId", "shortenPath", "shouldExpandByDefault",
    "splitKeepRight", "statusGlyph", "t", "theme", "toSlashCommand", "truncateToWidth",
    "tuiCommands", "visibleWidth", "wrapPlain", "wrapPlainLines",
  ],
  "@civaapple/qi-node/workspace": [
    "ContainerWorkspaceAdapter", "GitWorktreeAdapter", "LocalWorkspace",
    "SqliteEffectJournal", "effectIdempotencyKey", "effectIntentHash", "hostProcessRunner",
    "minimalHostEnvironment", "runHostProcess", "scrubCredentialEnvironment",
    "terminateProcessTree",
  ],
};

test("all controlled six-package runtime entrypoints are explicitly reviewed", async () => {
  for (const [packageName, expected] of Object.entries(expectedRuntimeExports)) {
    const packageModule = await import(packageName);
    assert.deepEqual(
      Object.keys(packageModule).sort(),
      [...expected].sort(),
      `${packageName} runtime exports changed; review and update its public API snapshot intentionally`,
    );
  }
});
